services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
    command: ./entrypoint.sh
